
import { GoogleGenAI } from "@google/genai";
import { AppSettings } from "../types";

export const generateImage = async (
  prompt: string,
  base64Image: string | null,
  settings: AppSettings
): Promise<string> => {
  // Use a new instance to ensure we pick up the latest API key (important for Pro model)
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const parts: any[] = [{ text: prompt }];
  
  if (base64Image) {
    // Extract mime type and data from the data URL
    const matches = base64Image.match(/^data:([a-zA-Z0-9]+\/[a-zA-Z0-9-.+]+);base64,(.+)$/);
    if (matches && matches.length === 3) {
      parts.push({
        inlineData: {
          mimeType: matches[1],
          data: matches[2]
        }
      });
    }
  }

  const config: any = {
    imageConfig: {
      aspectRatio: settings.aspectRatio,
    }
  };

  // Only gemini-3-pro-image-preview supports imageSize
  if (settings.model === 'gemini-3-pro-image-preview') {
    config.imageConfig.imageSize = settings.imageSize;
  }

  try {
    const response = await ai.models.generateContent({
      model: settings.model,
      contents: { parts },
      config,
    });

    if (!response.candidates || response.candidates.length === 0) {
      throw new Error("No image generated by the model.");
    }

    // Iterate through parts to find the image
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }

    throw new Error("No image data found in response.");
  } catch (error: any) {
    console.error("Gemini Generation Error:", error);
    throw error;
  }
};
